import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "./component/Header";
import "./globals.css";
import SearchWrapper from "./component/SearchWrapper";
import BottomTabsWrapper from "./component/BottomTabsWrapper";
import { Car, Heart, Home, User } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen text-textPrimary dark:text-slate-200">
          <Header hiddenRoutes={["/options"] as any}/>

          {/* Mobile Search (conditionally hidden on some routes) */}
          {/* <SearchWrapper hiddenRoutes={["/reels", ]} /> */}

          <main className="pb-24 max-w-7xl mx-auto">{children}</main>

          {/* Bottom Navigation */}
           <BottomTabsWrapper hiddenRoutes={["/reels", "/profile"]} />
        </div>
      </body>
    </html>
  );
}
